name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current version
        id: get_version
        run: |
          if [ -e version.txt ]; then
            echo "VERSION=0.15" >> $GITHUB_ENV
          else
            echo "VERSION=0.0" >> $GITHUB_ENV
          fi

          #  - name: Increment version
        #  id: increment_version
          # run: |
          #    run: echo "VERSION=$(awk 'BEGIN{print ENVIRON[\"VERSION\"]+0.1}')" >> $GITHUB_ENV
      - name: Set IMAGE_TAG variable
        run: echo "IMAGE_TAG=${{ env.VERSION }}" >> $GITHUB_ENV

      - name: Update version.txt file
        run: echo -n "booba" > version.txt
      - name: Debugging
        run: |
          pwd
          ls -la
          cat version.txt

      - name: Build and push Docker image
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          docker build -t skoopy365/webapp-py:${IMAGE_TAG} .
          docker login -u skoopy365 -p ${{ secrets.DOCKER_TOKEN }}
          docker push skoopy365/webapp-py:${IMAGE_TAG}

