name: Python application

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build and push Docker image
    - name: Build & Push Image
        env:
        IMAGE_TAG: ${{ github.sha }}
        run: |
        echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "skoopy365" --password-stdin
        docker image build -t skoopy365/webapp.py:${IMAGE_TAG} .
        docker push skoopy365/webapp.py:${IMAGE_TAG}
