name: Python application

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set IMAGE_TAG variable
      run: echo "1" >> ${{ env.IMAGE_TAG }}  
    - name: Build & Push Image
    - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            latest
            ${{ env.IMAGE_TAG }}
      # env:
        #  IMAGE_TAG: ${{ github.sha }}
        # run: |
        # echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "skoopy365" --password-stdin
        #  docker image build -t skoopy365/webapp-py:${IMAGE_TAG} .
        # docker push skoopy365/webapp-py:${IMAGE_TAG}
        #    uses: Charlyzzz/update-k8s-image:1.71
        #    name: update image Tag to ${IMAGE_TAG}
        #    with:
        #      manifest-path: argocd/1appdeploytest.yaml
        #      new-image-tag: ${IMAGE_TAG}
        #      name: app-test-1 

# Example of using the output
#- id: test
#  run: curl ${{ steps.update-image.outputs.old-image-tag }}    
